apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-orchestrator" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "olympe.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
spec:
  selector:
    name: {{ printf "%s-orchestrator" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
  ports:
    - name: app
      port: 8080
      targetPort: 8080
    - name: micrometer
      port: 8081
      targetPort: 8081

{{ if .Values.orchestrator.prometheus.enabled }}
{{- $replicaCount := .Values.orchestrator.replicas | int | default 1}}
{{- range $i, $e := until $replicaCount}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-orchestrator-prometheus" (include "olympe.fullname" $) | trunc 63 | trimSuffix "-" }}
spec:
  ports:
    - name: micrometer
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    statefulset.kubernetes.io/pod-name: {{ printf "%s-orchestrator-prometheus" (include "olympe.fullname" $) | trunc 63 | trimSuffix "-" }}
  clusterIP: None
  type: ClusterIP
{{- end }}
{{- end -}}