apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-orchestrator-config" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "olympe.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
data:
  {{- if .Values.orchestrator.haEnabled }}
  CLUSTERING_ENABLED: "true"
  HAZELCAST_SERVICE_NAME: {{ printf "%s-orchestrator-ha" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
  HAZELCAST_DNS_NAMESPACE: {{ .Release.Namespace }}
  CLUSTERING_REQUIRED_MEMBERS_COUNT: {{ .Values.orchestrator.replicas | quote }}
  {{- else }}
  CLUSTERING_ENABLED: "false"
  {{- end }}
  DB_HOSTNAME: {{ default "neo4j" .Values.orchestrator.neo4j.hostname }}
  DB_NAME: {{ default "neo4j" .Values.orchestrator.neo4j.dbName }}
  KUBERNETES_NAMESPACE: {{ .Release.Namespace }}
  RABBITMQ_HOST: {{ .Values.orchestrator.rabbitmq.host }}
  RABBITMQ_VIRTUAL_HOST: {{ default "orchestrator" .Values.orchestrator.rabbitmq.vhost }}
  RABBITMQ_ORCHESTRATOR_VHOST: {{ default "orchestrator" .Values.orchestrator.rabbitmq.orchestratorVhost }}
  RABBITMQ_PORT: {{ .Values.orchestrator.rabbitmq.port | quote }}
  RABBITMQ_PROTO: {{ default "amqp" .Values.orchestrator.rabbitmq.proto }}
  DB_URI_SCHEME: {{ .Values.orchestrator.neo4j.protocol }}
  {{- range $key, $val := .Values.orchestrator.configMapEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}