{{- if not .Values.orchestrator.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-orchestrator-secret" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "olympe.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
  annotations:
type: Opaque
data:
  DB_USER: {{ .Values.orchestrator.neo4j.dbUsername | b64enc | quote }}
  DB_PASSWORD: {{ .Values.orchestrator.neo4j.dbUserPassword | b64enc | quote }}
  RABBITMQ_USER: {{ .Values.orchestrator.rabbitmq.username | b64enc | quote }}
  RABBITMQ_PASSWORD: {{ .Values.orchestrator.rabbitmq.password | b64enc | quote }}
  RABBITMQ_ORCHESTRATOR_USER: {{ .Values.orchestrator.rabbitmq.orchestratorUsername | b64enc | quote }}
  RABBITMQ_ORCHESTRATOR_PASSWORD: {{ .Values.orchestrator.rabbitmq.orchestratorPassword | b64enc | quote }}
  {{- if .Values.orchestrator.drawPassword }}
  DRAW_PASSWORD: {{ .Values.orchestrator.drawPassword | b64enc | quote }}
  {{- else }}
  DRAW_PASSWORD: {{ template "olympe.drawPassword" . }}
  {{- end }}
{{- end }}