{{- if ne (len .Values.serviceApps) 0}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-nodes" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "olympe.labels" . | nindent 4 }}
    name: {{ printf "%s-nodes" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ default "1Gi" .Values.nodes.dataVolume.storage }}
  storageClassName: {{ default "standard" .Values.nodes.dataVolume.storageClassName }}
  volumeName: {{ printf "%s-nodes-pv" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
{{- end }}