apiVersion: v2
name: olympe
description: Helm chart for a Kubernetes implementation of an Olympe project
icon: https://d4i4w3v4.rocketcdn.me/wp-content/uploads/2020/01/Olympe_white.svg

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.0.10

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.0.0

dependencies:
  - condition: neo4j.enabled
    name: neo4j
    version: 4.4.9
    repository: https://neo4j-contrib.github.io/neo4j-helm
  - condition: rabbitmq.enabled
    name: rabbitmq
    version: 10.2.1
    repository: https://charts.bitnami.com/bitnami