{{- if not .Values.orchestrator.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-orchestrator-secret" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "olympe.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
  annotations:
type: Opaque
stringData:
  DB_USER: {{ default "neo4j" .Values.orchestrator.neo4j.dbUsername }}
  DB_PASSWORD: {{ default "olympe" .Values.orchestrator.neo4j.dbUserPassword }}
  RABBITMQ_USER: {{ default "guest" .Values.orchestrator.rabbitmq.username }}
  RABBITMQ_PASSWORD: {{ default "guest" .Values.orchestrator.rabbitmq.password }}
  RABBITMQ_ORCHESTRATOR_USER: {{ default "guest" .Values.orchestrator.rabbitmq.orchestratorUsername }}
  RABBITMQ_ORCHESTRATOR_PASSWORD: {{ default "guest" .Values.orchestrator.rabbitmq.orchestratorPassword }}
{{- end }}