apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-exec
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-secret
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]